#!/usr/bin/env bash
#
# Emits the Homebrew formula for a released version to stdout.
#
# One generator, used by both the release workflow and the local
# update-formula.sh, because they previously carried separate templates that
# drifted: the workflow's was macOS-only and would silently overwrite Linux
# support added by hand.
#
# Usage: gen-formula.sh --version X.Y.Z --checksums DIR
#
# DIR is searched recursively for dotdipper-<target>.tar.gz.sha256 files, so
# it accepts both the flat layout scripts/build-release.sh produces and the
# nested per-artifact layout actions/download-artifact produces.
#
# A target whose checksum is absent is omitted from the formula entirely. A
# formula that names a placeholder checksum is worse than one that does not
# offer the platform: the first fails at install time with a hash mismatch,
# the second fails immediately and legibly.
set -euo pipefail

VERSION=""
CHECKSUM_DIR=""

while [ $# -gt 0 ]; do
    case "$1" in
        --version) VERSION="$2"; shift 2 ;;
        --checksums) CHECKSUM_DIR="$2"; shift 2 ;;
        *) echo "unknown argument: $1" >&2; exit 1 ;;
    esac
done

[ -n "$VERSION" ] || { echo "error: --version is required" >&2; exit 1; }
[ -d "${CHECKSUM_DIR:-}" ] || { echo "error: --checksums must be a directory" >&2; exit 1; }

sha_for() {
    local target="$1"
    local file
    file=$(find "$CHECKSUM_DIR" -name "dotdipper-${target}.tar.gz.sha256" -type f 2>/dev/null | head -1)
    [ -n "$file" ] || return 1
    awk '{print $1}' "$file" | tr -d '[:space:]'
}

MACOS_ARM=$(sha_for aarch64-apple-darwin || true)
MACOS_X86=$(sha_for x86_64-apple-darwin || true)
LINUX_ARM=$(sha_for aarch64-unknown-linux-gnu || true)
LINUX_X86=$(sha_for x86_64-unknown-linux-gnu || true)

if [ -z "$MACOS_ARM" ] && [ -z "$MACOS_X86" ] && [ -z "$LINUX_ARM" ] && [ -z "$LINUX_X86" ]; then
    echo "error: no checksum files found under $CHECKSUM_DIR" >&2
    exit 1
fi

url_for() {
    echo "https://github.com/psyysp/dotdipper/releases/download/v${VERSION}/dotdipper-$1.tar.gz"
}

emit_platform_block() {
    local os="$1" arm_sha="$2" x86_sha="$3" arm_target="$4" x86_target="$5"
    [ -n "$arm_sha" ] || [ -n "$x86_sha" ] || return 0
    echo "  on_${os} do"
    if [ -n "$arm_sha" ]; then
        echo "    on_arm do"
        echo "      url \"$(url_for "$arm_target")\""
        echo "      sha256 \"${arm_sha}\""
        echo "    end"
    fi
    if [ -n "$x86_sha" ]; then
        echo "    on_intel do"
        echo "      url \"$(url_for "$x86_target")\""
        echo "      sha256 \"${x86_sha}\""
        echo "    end"
    fi
    echo "  end"
    echo
}

cat <<HEADER
# Homebrew formula for dotdipper.
# Generated by scripts/gen-formula.sh — do not edit by hand.
#
#   brew install psyysp/dotdipper/dotdipper

class Dotdipper < Formula
  desc "A safe, deterministic, and feature-rich dotfiles manager built in Rust"
  homepage "https://github.com/psyysp/dotdipper"
  version "${VERSION}"
  license "MIT"

HEADER

emit_platform_block macos "$MACOS_ARM" "$MACOS_X86" aarch64-apple-darwin x86_64-apple-darwin
emit_platform_block linux "$LINUX_ARM" "$LINUX_X86" aarch64-unknown-linux-gnu x86_64-unknown-linux-gnu

# Only constrain the platform when one of them genuinely has no artifact.
if [ -z "$LINUX_ARM" ] && [ -z "$LINUX_X86" ]; then
    echo "  depends_on :macos"
elif [ -z "$MACOS_ARM" ] && [ -z "$MACOS_X86" ]; then
    echo "  depends_on :linux"
fi

cat <<'FOOTER'
  depends_on "age"

  def install
    bin.install "dotdipper"
  end

  def caveats
    <<~EOS
      Dotdipper has been installed.

      To get started:
        dotdipper init

      For help:
        dotdipper --help
    EOS
  end

  test do
    assert_match "dotdipper", shell_output("#{bin}/dotdipper --version")
  end
end
FOOTER
