//! Sanitized public mirror of the private compiled store.
//!
//! `dotdipper push` keeps one repository that holds everything, including the
//! files that make a restore actually work: `.ssh/config`, `.gitconfig`, the
//! Brewfile and the app manifest. Those are exactly the files that must not be
//! public — they carry an email address, a private network's hostnames, and a
//! version-accurate inventory of installed software.
//!
//! `dotdipper publish` derives a second tree from the same store:
//!
//! 1. **Exclude** — paths matching `[public] exclude` are withheld entirely.
//! 2. **Redact** — the survivors are rewritten by the built-in redactors and
//!    any user `redact` rules.
//! 3. **Scan** — the finished tree is scanned for secrets and PII. Any hit
//!    aborts the publish before anything is written or pushed.
//!
//! Step 3 is the point. Steps 1 and 2 are a denylist, and a denylist always
//! has gaps; the scan is what turns a gap into a failed publish rather than a
//! leak. Nothing reaches the public remote unless the scan comes back clean.

use anyhow::{Context, Result};
use regex::Regex;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use crate::cfg::{Config, PublicConfig};
use crate::ui;

/// How many redactions one rule made in one file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Redaction {
    pub rule: String,
    pub count: usize,
}

/// A file withheld from the public tree, and why.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Exclusion {
    pub path: PathBuf,
    pub reason: String,
}

/// A scanner hit. Any unallowed finding blocks the publish.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Finding {
    /// Stable short id, so a reviewed finding can be allowed by name.
    pub id: String,
    pub path: PathBuf,
    pub line: usize,
    pub kind: String,
    /// Already masked — never the raw matched text.
    pub excerpt: String,
}

/// One approved path in the allowlist.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct AllowedFile {
    pub path: String,
    /// Redactions applied when this entry was reviewed, as `rule xN`.
    ///
    /// Recorded for transparency, not enforcement. A diff that shows a file's
    /// redactions dropping to none is the visible signal that a rule stopped
    /// matching — the kind of silent regression a denylist alone hides.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub redactions: Vec<String>,
}

/// The reviewed record of exactly what may be published.
///
/// Generated by `dotdipper publish --review` rather than hand-written, so the
/// allowlist stays convenient, but enforced on every publish, so a file that
/// appears in the store later cannot publish itself unnoticed.
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct Allowlist {
    #[serde(default)]
    pub generated: String,
    #[serde(default)]
    pub files: Vec<AllowedFile>,
    /// Paths withheld at review time, with the reason. Informational: it makes
    /// the allowlist a complete account of the store, not just the public part.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub withheld: Vec<AllowedFile>,
}

impl Allowlist {
    pub fn contains(&self, rel: &Path) -> bool {
        let key = rel.to_string_lossy();
        self.files.iter().any(|f| f.path == key)
    }

    pub fn load(path: &Path) -> Result<Option<Self>> {
        if !path.exists() {
            return Ok(None);
        }
        let text = fs::read_to_string(path)
            .with_context(|| format!("Failed to read allowlist {}", path.display()))?;
        let parsed: Allowlist = toml::from_str(&text)
            .with_context(|| format!("Failed to parse allowlist {}", path.display()))?;
        Ok(Some(parsed))
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        let body = toml::to_string_pretty(self).context("Failed to serialize allowlist")?;
        let header = "# Generated by `dotdipper publish --review`.\n\
                      #\n\
                      # Every path under [[files]] is published to the public mirror; anything\n\
                      # else is withheld, including files added to the store later. `redactions`\n\
                      # records what was scrubbed from each file at review time — if an entry\n\
                      # loses its redactions in a diff, a rule stopped matching.\n\
                      #\n\
                      # Review this file before committing it. Re-run --review after adding\n\
                      # dotfiles you want published.\n\n";
        fs::write(path, format!("{header}{body}"))
            .with_context(|| format!("Failed to write allowlist {}", path.display()))?;
        Ok(())
    }
}

/// Resolves the allowlist path from config, relative to the dotdipper base dir.
pub fn allowlist_path(config: &Config) -> Result<PathBuf> {
    let name = config
        .public
        .as_ref()
        .map(|p| p.allowlist.clone())
        .unwrap_or_else(|| PublicConfig::default().allowlist);
    let candidate = PathBuf::from(&name);
    if candidate.is_absolute() {
        return Ok(candidate);
    }
    Ok(crate::paths::base_dir()?.join(candidate))
}

/// The full result of deriving a public tree, before anything is pushed.
#[derive(Debug, Default)]
pub struct Plan {
    pub published: Vec<PathBuf>,
    pub excluded: Vec<Exclusion>,
    pub redactions: BTreeMap<PathBuf, Vec<Redaction>>,
    pub findings: Vec<Finding>,
    /// Sanitized paths that are not on the allowlist. Withheld, and surfaced
    /// so the user knows review is pending rather than silently losing them.
    pub pending_review: Vec<PathBuf>,
}

impl Plan {
    pub fn is_clean(&self) -> bool {
        self.findings.is_empty()
    }

    /// Builds the allowlist this run would approve.
    pub fn to_allowlist(&self) -> Allowlist {
        let describe = |p: &PathBuf| -> Vec<String> {
            self.redactions
                .get(p)
                .map(|rs| {
                    rs.iter()
                        .map(|r| format!("{} x{}", r.rule, r.count))
                        .collect()
                })
                .unwrap_or_default()
        };

        let mut files: Vec<AllowedFile> = self
            .published
            .iter()
            .chain(self.pending_review.iter())
            .map(|p| AllowedFile {
                path: p.to_string_lossy().to_string(),
                redactions: describe(p),
            })
            .collect();
        files.sort_by(|a, b| a.path.cmp(&b.path));
        files.dedup_by(|a, b| a.path == b.path);

        Allowlist {
            generated: chrono::Utc::now().to_rfc3339(),
            files,
            withheld: self
                .excluded
                .iter()
                .map(|e| AllowedFile {
                    path: e.path.to_string_lossy().to_string(),
                    redactions: vec![e.reason.clone()],
                })
                .collect(),
        }
    }

    pub fn redaction_total(&self) -> usize {
        self.redactions
            .values()
            .flat_map(|rs| rs.iter())
            .map(|r| r.count)
            .sum()
    }
}

/// A compiled redaction rule.
struct Rule {
    name: &'static str,
    /// `None` applies to every text file.
    path: Option<&'static str>,
    pattern: Regex,
    replacement: &'static str,
}

/// Redactors that run unless `builtin_redactors = false`.
///
/// These target the categories that a personal dotfiles tree reliably leaks.
/// Over-redaction here is cheap; a miss is a disclosure, so the patterns are
/// deliberately broad.
fn builtin_rules() -> Vec<Rule> {
    vec![
        // git identity: `name = ...` / `email = ...` under [user].
        //
        // The optional `[#;]` matters. Git configs routinely keep a
        // commented-out copy of the identity ("# name = realname"), and a bare
        // username is not something the scanner can recognise, so a miss here
        // is a silent leak rather than a blocked publish.
        Rule {
            name: "gitconfig-identity",
            path: Some(".gitconfig"),
            pattern: Regex::new(r"(?mi)^(\s*[#;]?\s*(?:name|email)\s*=\s*).+$").unwrap(),
            replacement: "${1}<redacted>",
        },
        // Machine name recorded at capture time.
        Rule {
            name: "apps-hostname",
            path: Some("apps_manifest.toml"),
            pattern: Regex::new(r#"(?mi)^(hostname\s*=\s*).+$"#).unwrap(),
            replacement: "${1}\"<redacted>\"",
        },
        // SSH endpoints, if the file is published rather than excluded.
        Rule {
            name: "ssh-endpoints",
            path: Some(".ssh/config"),
            pattern: Regex::new(
                r"(?mi)^(\s*(?:hostname|user|proxyjump|proxycommand|identityfile)\s+).+$",
            )
            .unwrap(),
            replacement: "${1}<redacted>",
        },
        // Tailscale MagicDNS names disclose the tailnet id.
        Rule {
            name: "tailnet-hostname",
            path: None,
            pattern: Regex::new(r"[A-Za-z0-9_-]+\.tail[0-9a-f]+\.ts\.net").unwrap(),
            replacement: "<redacted>.ts.net",
        },
        // Absolute home paths carry the local account name.
        Rule {
            name: "home-paths",
            path: None,
            pattern: Regex::new(r"/(?:Users|home)/[A-Za-z0-9._-]+").unwrap(),
            replacement: "$$HOME",
        },
        // Any address. Over-broad on purpose: a redacted vendor address in a
        // third-party file is cosmetic, a published personal one is not.
        Rule {
            name: "email-address",
            path: None,
            pattern: Regex::new(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}").unwrap(),
            replacement: "<redacted>@example.invalid",
        },
    ]
}

/// Literal identifiers belonging to this account and machine.
///
/// A regex can describe the *shape* of a token, but a bare username or device
/// name has no shape — `psy@MacBook-Air` in a prompt string and
/// `username = "someuser"` in a config are ordinary words. Rather than guess,
/// publish scrubs the actual values it can read from the environment, and the
/// scanner re-checks the same list so a redaction miss blocks the publish
/// instead of shipping.
///
/// Terms shorter than three characters are dropped: redacting every "al" in
/// the tree would destroy it, and such a term is not identifying anyway.
pub(crate) fn identity_terms(config: &Config) -> Vec<String> {
    let mut terms: Vec<String> = Vec::new();

    if let Some(home) = dirs::home_dir() {
        if let Some(user) = home.file_name().and_then(|s| s.to_str()) {
            terms.push(user.to_string());
        }
    }
    if let Ok(user) = std::env::var("USER") {
        terms.push(user);
    }
    if let Some(gh) = &config.github.username {
        terms.push(gh.clone());
    }
    if let Some(host) = hostname::get().ok().and_then(|h| h.into_string().ok()) {
        // "PSYs-MacBook-Air.local" also yields "PSYs-MacBook-Air", since the
        // short form is what appears in prompts and manifests.
        if let Some(short) = host.strip_suffix(".local") {
            terms.push(short.to_string());
        }
        terms.push(host);
    }

    terms.retain(|t| t.chars().count() >= 3);
    terms.sort_by_key(|t| std::cmp::Reverse(t.chars().count()));
    terms.dedup();
    terms
}

/// Case-insensitive, boundary-anchored pattern for one literal identity term.
fn identity_regex(term: &str) -> Option<Regex> {
    Regex::new(&format!(r"(?i)\b{}\b", regex::escape(term))).ok()
}

/// Patterns that must not survive into a public tree.
///
/// Ordered most specific first so the reported `kind` is the useful one.
fn scanner_patterns() -> Vec<(&'static str, Regex)> {
    vec![
        (
            "private-key",
            Regex::new(r"-----BEGIN [A-Z ]*PRIVATE KEY-----").unwrap(),
        ),
        (
            "stripe-key",
            Regex::new(r"\b[sprk]k_(?:live|test)_[A-Za-z0-9]{20,}").unwrap(),
        ),
        (
            "github-token",
            Regex::new(
                r"\b(?:ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{20,}|\bgithub_pat_[A-Za-z0-9_]{20,}",
            )
            .unwrap(),
        ),
        (
            "aws-key",
            Regex::new(r"\b(?:AKIA|ASIA)[0-9A-Z]{16}\b").unwrap(),
        ),
        (
            "slack-token",
            Regex::new(r"\bxox[baprs]-[A-Za-z0-9-]{10,}").unwrap(),
        ),
        (
            "google-api-key",
            Regex::new(r"\bAIza[0-9A-Za-z_-]{35}\b").unwrap(),
        ),
        (
            "anthropic-key",
            Regex::new(r"\bsk-ant-[A-Za-z0-9_-]{20,}").unwrap(),
        ),
        (
            "gitlab-token",
            Regex::new(r"\bglpat-[A-Za-z0-9_-]{20,}").unwrap(),
        ),
        ("npm-token", Regex::new(r"\bnpm_[A-Za-z0-9]{36}\b").unwrap()),
        (
            "jwt",
            Regex::new(r"\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}").unwrap(),
        ),
        (
            "oauth-token-field",
            Regex::new(r#""(?:access_token|refresh_token|id_token|client_secret)"\s*:"#).unwrap(),
        ),
        (
            "tailnet-hostname",
            Regex::new(r"[A-Za-z0-9_-]+\.tail[0-9a-f]+\.ts\.net").unwrap(),
        ),
        (
            "email-address",
            Regex::new(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}").unwrap(),
        ),
        (
            "home-path",
            Regex::new(r"/(?:Users|home)/[A-Za-z0-9._-]+").unwrap(),
        ),
        (
            "private-ip",
            Regex::new(r"\b(?:10\.\d{1,3}|192\.168|172\.(?:1[6-9]|2\d|3[01]))\.\d{1,3}\.\d{1,3}\b")
                .unwrap(),
        ),
    ]
}

/// The replacement text the redactors emit. The scanner would otherwise flag
/// its own output (`<redacted>@example.invalid` looks like an address).
fn is_redaction_artifact(matched: &str) -> bool {
    matched.contains("<redacted>") || matched.ends_with("@example.invalid")
}

/// Short stable id for a finding, so `allow` entries survive re-runs.
fn finding_id(path: &Path, kind: &str, line: usize) -> String {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in path
        .to_string_lossy()
        .as_bytes()
        .iter()
        .chain(kind.as_bytes())
        .chain(line.to_string().as_bytes())
    {
        hash ^= *byte as u64;
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    format!("{:08x}", (hash >> 32) as u32)
}

/// Masks a matched secret so the report never reprints it in full.
fn mask(matched: &str) -> String {
    let chars: Vec<char> = matched.chars().collect();
    if chars.len() <= 8 {
        return "*".repeat(chars.len());
    }
    let head: String = chars[..2].iter().collect();
    let tail: String = chars[chars.len() - 2..].iter().collect();
    format!("{}…{} ({} chars)", head, tail, chars.len())
}

fn matches_glob(pattern: &str, rel: &Path) -> bool {
    glob::Pattern::new(pattern)
        .map(|p| p.matches_path(rel))
        .unwrap_or(false)
}

/// Heuristic: treat a file with a NUL byte in its first block as binary.
/// Binary files are copied verbatim and never redacted, so they must be
/// excluded rather than relied on to be clean.
fn is_binary(bytes: &[u8]) -> bool {
    bytes.iter().take(8000).any(|b| *b == 0)
}

/// Applies the built-in and configured rules to one file's text.
fn redact_text(
    rel: &Path,
    text: &str,
    cfg: &PublicConfig,
    identity: &[String],
) -> (String, Vec<Redaction>) {
    let mut out = text.to_string();
    let mut applied = Vec::new();

    if cfg.builtin_redactors {
        for rule in builtin_rules() {
            if let Some(p) = rule.path {
                if !matches_glob(p, rel) {
                    continue;
                }
            }
            let count = rule.pattern.find_iter(&out).count();
            if count > 0 {
                out = rule
                    .pattern
                    .replace_all(&out, rule.replacement)
                    .into_owned();
                applied.push(Redaction {
                    rule: rule.name.to_string(),
                    count,
                });
            }
        }
    }

    // Literal identity terms run after the pattern rules on purpose. Scrubbing
    // "psy" first would turn "/Users/psy" into "/Users/<redacted>", which the
    // home-paths rule can no longer collapse to "$HOME".
    if cfg.builtin_redactors {
        let mut identity_hits = 0usize;
        for term in identity {
            let Some(re) = identity_regex(term) else {
                continue;
            };
            let count = re.find_iter(&out).count();
            if count > 0 {
                out = re.replace_all(&out, "<redacted>").into_owned();
                identity_hits += count;
            }
        }
        if identity_hits > 0 {
            applied.push(Redaction {
                rule: "identity-terms".to_string(),
                count: identity_hits,
            });
        }
    }

    for rule in &cfg.redact {
        if let Some(p) = &rule.path {
            if !matches_glob(p, rel) {
                continue;
            }
        }
        let Ok(re) = Regex::new(&rule.pattern) else {
            ui::warn(&format!(
                "Skipping redact rule '{}': invalid regex {}",
                rule.name, rule.pattern
            ));
            continue;
        };
        let count = re.find_iter(&out).count();
        if count > 0 {
            out = re.replace_all(&out, rule.replacement.as_str()).into_owned();
            applied.push(Redaction {
                rule: rule.name.clone(),
                count,
            });
        }
    }

    (out, applied)
}

/// Scans finished public text for anything that must not ship.
fn scan_text(rel: &Path, text: &str, allow: &[String], identity: &[String]) -> Vec<Finding> {
    let mut findings = Vec::new();
    let mut patterns = scanner_patterns();
    for term in identity {
        if let Some(re) = identity_regex(term) {
            patterns.push(("identity-term", re));
        }
    }

    for (lineno, line) in text.lines().enumerate() {
        for (kind, re) in &patterns {
            for m in re.find_iter(line) {
                if is_redaction_artifact(m.as_str()) {
                    continue;
                }
                let id = finding_id(rel, kind, lineno + 1);
                if allow.iter().any(|a| a == &id) {
                    continue;
                }
                findings.push(Finding {
                    id,
                    path: rel.to_path_buf(),
                    line: lineno + 1,
                    kind: (*kind).to_string(),
                    excerpt: mask(m.as_str()),
                });
                // One finding per kind per line keeps the report readable.
                break;
            }
        }
    }

    findings
}

/// Derives the public tree from `source`, writing it to `dest` when `dest` is
/// given. Returns the plan either way, so `--dry-run` shares this exact path.
///
/// Nothing is written until the scan is clean: the tree is built in memory
/// first, and a dirty scan returns before `dest` is touched.
pub fn build(
    source: &Path,
    dest: Option<&Path>,
    config: &Config,
    allowlist: Option<&Allowlist>,
) -> Result<Plan> {
    let public = config.public.clone().unwrap_or_default();
    let identity = if public.builtin_redactors {
        identity_terms(config)
    } else {
        Vec::new()
    };
    let mut plan = Plan::default();
    let mut staged: Vec<(PathBuf, Vec<u8>)> = Vec::new();

    for entry in walkdir::WalkDir::new(source)
        .into_iter()
        .filter_entry(|e| e.file_name() != std::ffi::OsStr::new(".git"))
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().is_file())
    {
        let Ok(rel) = entry.path().strip_prefix(source) else {
            continue;
        };

        if let Some(pattern) = public
            .exclude
            .iter()
            .find(|pattern| matches_glob(pattern, rel))
        {
            plan.excluded.push(Exclusion {
                path: rel.to_path_buf(),
                reason: format!("public.exclude '{}'", pattern),
            });
            continue;
        }

        let bytes = fs::read(entry.path())
            .with_context(|| format!("Failed to read {}", entry.path().display()))?;

        // Binary content cannot be redacted or meaningfully scanned. Withhold
        // it rather than ship bytes nobody has inspected.
        if is_binary(&bytes) {
            plan.excluded.push(Exclusion {
                path: rel.to_path_buf(),
                reason: "binary file (cannot be redacted or scanned)".to_string(),
            });
            continue;
        }

        let text = String::from_utf8_lossy(&bytes).into_owned();
        let (redacted, applied) = redact_text(rel, &text, &public, &identity);
        if !applied.is_empty() {
            plan.redactions.insert(rel.to_path_buf(), applied);
        }

        plan.findings
            .extend(scan_text(rel, &redacted, &public.allow, &identity));

        // The allowlist gates paths, the scanner gates content. A path nobody
        // has reviewed is withheld even when it scans clean, so a newly
        // captured file cannot publish itself on the next run.
        if let Some(list) = allowlist {
            if !list.contains(rel) {
                plan.pending_review.push(rel.to_path_buf());
                continue;
            }
        }

        plan.published.push(rel.to_path_buf());
        staged.push((rel.to_path_buf(), redacted.into_bytes()));
    }

    plan.published.sort();
    plan.pending_review.sort();
    plan.excluded.sort_by(|a, b| a.path.cmp(&b.path));
    plan.findings
        .sort_by(|a, b| (&a.path, a.line).cmp(&(&b.path, b.line)));

    // Fail closed: a dirty scan writes nothing.
    if !plan.is_clean() {
        return Ok(plan);
    }

    if let Some(dest) = dest {
        write_tree(dest, &staged)?;
    }

    Ok(plan)
}

/// Replaces `dest`'s contents with the staged tree, preserving its `.git`.
fn write_tree(dest: &Path, staged: &[(PathBuf, Vec<u8>)]) -> Result<()> {
    fs::create_dir_all(dest)
        .with_context(|| format!("Failed to create public tree at {}", dest.display()))?;

    // Clear the previous contents so a file that stops qualifying disappears
    // instead of lingering, which is the same bug the private store had.
    for entry in fs::read_dir(dest)? {
        let entry = entry?;
        if entry.file_name() == std::ffi::OsStr::new(".git") {
            continue;
        }
        let path = entry.path();
        if path.is_dir() {
            fs::remove_dir_all(&path)?;
        } else {
            fs::remove_file(&path)?;
        }
    }

    for (rel, bytes) in staged {
        let out = dest.join(rel);
        if let Some(parent) = out.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&out, bytes).with_context(|| format!("Failed to write {}", out.display()))?;
    }

    Ok(())
}

/// Where the public tree is staged for the active profile.
pub fn public_dir() -> Result<PathBuf> {
    Ok(crate::profiles::active_store_paths()?
        .compiled
        .parent()
        .context("Failed to resolve profile directory")?
        .join("public"))
}

/// Prints the plan in the same shape for dry runs and real publishes.
pub fn report(plan: &Plan) {
    for (path, rules) in &plan.redactions {
        let names: Vec<String> = rules
            .iter()
            .map(|r| format!("{} x{}", r.rule, r.count))
            .collect();
        ui::hint(&format!(
            "redact  {}  [{}]",
            path.display(),
            names.join(", ")
        ));
    }
    for ex in &plan.excluded {
        ui::hint(&format!("exclude {}  ({})", ex.path.display(), ex.reason));
    }
    for path in &plan.pending_review {
        ui::warn(&format!(
            "pending {}  (not on the allowlist)",
            path.display()
        ));
    }
    ui::info(&format!(
        "{} file(s) to publish, {} withheld, {} awaiting review, {} redaction(s)",
        plan.published.len(),
        plan.excluded.len(),
        plan.pending_review.len(),
        plan.redaction_total()
    ));
    if !plan.pending_review.is_empty() {
        ui::hint("Run 'dotdipper publish --review' to inspect and allow the pending files.");
    }
}

/// Renders blocking findings and the exact way to accept one.
pub fn report_findings(plan: &Plan) {
    ui::warn(&format!(
        "Publish blocked: {} finding(s) in the sanitized tree",
        plan.findings.len()
    ));
    for f in &plan.findings {
        println!(
            "  [{}] {}:{}  {}  {}",
            f.id,
            f.path.display(),
            f.line,
            f.kind,
            f.excerpt
        );
    }
    ui::hint("Fix by excluding the file, adding a [[public.redact]] rule, or —");
    ui::hint("after reviewing it — allowing that one id with --allow-finding <id>.");
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cfg::RedactRule;

    /// Test shims: these cases exercise the pattern rules, so they pass an
    /// empty identity list. Identity scrubbing has its own tests below.
    fn redact_text_t(rel: &Path, text: &str, cfg: &PublicConfig) -> (String, Vec<Redaction>) {
        redact_text(rel, text, cfg, &[])
    }

    fn scan_text_t(rel: &Path, text: &str, allow: &[String]) -> Vec<Finding> {
        scan_text(rel, text, allow, &[])
    }

    fn cfg_with(public: PublicConfig) -> Config {
        Config {
            public: Some(public),
            ..Default::default()
        }
    }

    #[test]
    fn builtin_redactors_strip_identity_and_hostnames() {
        let public = PublicConfig::default();

        let (out, applied) = redact_text_t(
            Path::new(".gitconfig"),
            "[user]\n\tname = Real Person\n\temail = real.person@gmail.com\n",
            &public,
        );
        assert!(!out.contains("Real Person"));
        assert!(!out.contains("real.person@gmail.com"));
        assert!(applied.iter().any(|r| r.rule == "gitconfig-identity"));

        // Commented-out identity lines leak too. A bare username matches no
        // scanner pattern, so missing this one fails open.
        let (out, _) = redact_text_t(
            Path::new(".gitconfig"),
            "[user]\n\tname = Shown\n# \tname = Hidden Person\n;\temail = old@host.tld\n",
            &public,
        );
        assert!(
            !out.contains("Hidden Person"),
            "commented name survived: {out}"
        );
        assert!(!out.contains("old@host.tld"));

        let (out, _) = redact_text_t(
            Path::new("apps_manifest.toml"),
            "[meta]\nhostname = \"Someones-MacBook-Air.local\"\n",
            &public,
        );
        assert!(!out.contains("Someones-MacBook-Air"));
    }

    #[test]
    fn builtin_redactors_strip_tailnet_and_home_paths() {
        let public = PublicConfig::default();
        let (out, _) = redact_text_t(
            Path::new("notes.txt"),
            "ssh box.tail35163d.ts.net\nsource /Users/someone/.config/x\n",
            &public,
        );
        assert!(!out.contains("tail35163d"));
        assert!(!out.contains("/Users/someone"));
        assert!(out.contains("$HOME/.config/x"));
    }

    #[test]
    fn scanner_catches_a_secret_the_redactors_missed() {
        let findings = scan_text_t(
            Path::new("app.conf"),
            "key = sk_test_51TTyj0JS2XS3PL4oNvW5fK2npQ62FLyqHI9VUebGWaKWdlbpv1NR\n",
            &[],
        );
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].kind, "stripe-key");
        // The report must never reprint the secret in full.
        assert!(!findings[0].excerpt.contains("51TTyj0JS2XS3PL4o"));
    }

    #[test]
    fn scanner_ignores_its_own_redaction_output() {
        let public = PublicConfig::default();
        let (out, _) = redact_text_t(
            Path::new(".gitconfig"),
            "[user]\n\temail = someone@example.com\n",
            &public,
        );
        assert!(
            scan_text_t(Path::new(".gitconfig"), &out, &[]).is_empty(),
            "redacted output must not trip the scanner that follows it"
        );
    }

    #[test]
    fn allowing_a_finding_id_suppresses_only_that_finding() {
        let text = "contact = someone@example.com\nkey = AKIAIOSFODNN7EXAMPLE\n";
        let all = scan_text_t(Path::new("f.conf"), text, &[]);
        assert_eq!(all.len(), 2);

        let allowed = vec![all[0].id.clone()];
        let rest = scan_text_t(Path::new("f.conf"), text, &allowed);
        assert_eq!(rest.len(), 1, "only the allowed id should be suppressed");
        assert_ne!(rest[0].id, all[0].id);
    }

    #[test]
    fn finding_ids_are_stable_across_runs() {
        let text = "key = AKIAIOSFODNN7EXAMPLE\n";
        let a = scan_text_t(Path::new("f.conf"), text, &[]);
        let b = scan_text_t(Path::new("f.conf"), text, &[]);
        assert_eq!(a[0].id, b[0].id);
    }

    #[test]
    fn dirty_scan_writes_nothing_to_disk() {
        let src = tempfile::TempDir::new().unwrap();
        let dst = tempfile::TempDir::new().unwrap();
        // A secret the redactors have no rule for.
        fs::write(
            src.path().join("leaky.conf"),
            "token = ghp_ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789\n",
        )
        .unwrap();

        let plan = build(
            src.path(),
            Some(dst.path()),
            &cfg_with(PublicConfig::default()),
            None,
        )
        .unwrap();

        assert!(!plan.is_clean());
        assert_eq!(plan.findings[0].kind, "github-token");
        assert!(
            !dst.path().join("leaky.conf").exists(),
            "a blocked publish must not write the offending tree"
        );
    }

    #[test]
    fn clean_tree_is_written_and_excluded_paths_are_withheld() {
        let src = tempfile::TempDir::new().unwrap();
        let dst = tempfile::TempDir::new().unwrap();
        fs::create_dir_all(src.path().join(".ssh")).unwrap();
        fs::write(
            src.path().join(".ssh/config"),
            "Host a\n  HostName private.internal\n",
        )
        .unwrap();
        fs::write(src.path().join("manifest.lock"), "{}\n").unwrap();
        fs::write(src.path().join(".vimrc"), "set number\n").unwrap();
        fs::write(src.path().join(".gitconfig"), "[user]\n\temail = a@b.com\n").unwrap();

        let plan = build(
            src.path(),
            Some(dst.path()),
            &cfg_with(PublicConfig::default()),
            None,
        )
        .unwrap();

        assert!(plan.is_clean(), "findings: {:?}", plan.findings);
        assert!(dst.path().join(".vimrc").exists());
        assert!(dst.path().join(".gitconfig").exists());
        assert!(!dst.path().join(".ssh/config").exists());
        assert!(!dst.path().join("manifest.lock").exists());
        assert!(!fs::read_to_string(dst.path().join(".gitconfig"))
            .unwrap()
            .contains("a@b.com"));
    }

    #[test]
    fn binary_files_are_withheld_rather_than_shipped_unscanned() {
        let src = tempfile::TempDir::new().unwrap();
        let dst = tempfile::TempDir::new().unwrap();
        fs::write(src.path().join("db.mdb"), b"\x00\x01binary\x00payload").unwrap();

        let plan = build(
            src.path(),
            Some(dst.path()),
            &cfg_with(PublicConfig::default()),
            None,
        )
        .unwrap();

        assert!(!dst.path().join("db.mdb").exists());
        assert!(plan
            .excluded
            .iter()
            .any(|e| e.path == Path::new("db.mdb") && e.reason.contains("binary")));
    }

    #[test]
    fn rebuilding_drops_files_that_no_longer_qualify() {
        let src = tempfile::TempDir::new().unwrap();
        let dst = tempfile::TempDir::new().unwrap();
        fs::write(src.path().join("a.conf"), "a = 1\n").unwrap();
        fs::write(src.path().join("b.conf"), "b = 2\n").unwrap();
        build(
            src.path(),
            Some(dst.path()),
            &cfg_with(PublicConfig::default()),
            None,
        )
        .unwrap();
        assert!(dst.path().join("b.conf").exists());

        fs::remove_file(src.path().join("b.conf")).unwrap();
        build(
            src.path(),
            Some(dst.path()),
            &cfg_with(PublicConfig::default()),
            None,
        )
        .unwrap();

        assert!(dst.path().join("a.conf").exists());
        assert!(
            !dst.path().join("b.conf").exists(),
            "stale file must not linger in the public tree"
        );
    }

    #[test]
    fn identity_terms_are_scrubbed_where_no_pattern_could_match() {
        let public = PublicConfig::default();
        let identity = vec!["someuser".to_string(), "Someones-MacBook-Air".to_string()];

        // Both of these are bare words. No secret pattern matches them, so
        // without literal scrubbing they would publish silently.
        let (out, applied) = redact_text(
            Path::new("prompt.conf"),
            "prin \"$(color 2)someuser$(color 7)@Someones-MacBook-Air\"\nusername = \"someuser\"\n",
            &public,
            &identity,
        );

        assert!(!out.contains("someuser"));
        assert!(!out.contains("Someones-MacBook-Air"));
        assert!(applied.iter().any(|r| r.rule == "identity-terms"));
    }

    #[test]
    fn identity_scrubbing_respects_word_boundaries() {
        let public = PublicConfig::default();
        let identity = vec!["psy".to_string()];
        let (out, _) = redact_text(
            Path::new("notes.txt"),
            "psychology is unaffected; psy is not\n",
            &public,
            &identity,
        );
        assert!(out.contains("psychology is unaffected"));
        assert!(!out.contains("; psy is"));
    }

    #[test]
    fn scanner_blocks_an_identity_term_that_redaction_missed() {
        let identity = vec!["someuser".to_string()];
        let findings = scan_text(Path::new("f.conf"), "owner: someuser\n", &[], &identity);
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].kind, "identity-term");
    }

    #[test]
    fn short_identity_terms_are_ignored() {
        // A two-character username would otherwise shred unrelated text.
        let terms = {
            let mut c = Config::default();
            c.github.username = Some("ab".to_string());
            identity_terms(&c)
        };
        assert!(!terms.iter().any(|t| t == "ab"));
    }

    #[test]
    fn allowlist_withholds_paths_nobody_reviewed() {
        let src = tempfile::TempDir::new().unwrap();
        let dst = tempfile::TempDir::new().unwrap();
        fs::write(src.path().join("approved.conf"), "a = 1\n").unwrap();
        // A file that showed up in the store after the last review. It scans
        // clean, and it must still be withheld.
        fs::write(src.path().join("brand-new.conf"), "b = 2\n").unwrap();

        let list = Allowlist {
            generated: String::new(),
            files: vec![AllowedFile {
                path: "approved.conf".to_string(),
                redactions: vec![],
            }],
            withheld: vec![],
        };

        let plan = build(
            src.path(),
            Some(dst.path()),
            &cfg_with(PublicConfig::default()),
            Some(&list),
        )
        .unwrap();

        assert!(dst.path().join("approved.conf").exists());
        assert!(
            !dst.path().join("brand-new.conf").exists(),
            "an unreviewed path must not publish itself"
        );
        assert_eq!(plan.pending_review, vec![PathBuf::from("brand-new.conf")]);
    }

    #[test]
    fn generated_allowlist_records_paths_and_their_redactions() {
        let src = tempfile::TempDir::new().unwrap();
        fs::write(src.path().join(".vimrc"), "set number\n").unwrap();
        fs::write(src.path().join(".gitconfig"), "[user]\n\temail = a@b.com\n").unwrap();

        // No allowlist yet: this is what --review sees.
        let plan = build(src.path(), None, &cfg_with(PublicConfig::default()), None).unwrap();
        let list = plan.to_allowlist();

        let gitconfig = list
            .files
            .iter()
            .find(|f| f.path == ".gitconfig")
            .expect(".gitconfig should be listed");
        assert!(
            gitconfig
                .redactions
                .iter()
                .any(|r| r.contains("gitconfig-identity")),
            "the allowlist must show what was scrubbed: {:?}",
            gitconfig.redactions
        );

        let vimrc = list.files.iter().find(|f| f.path == ".vimrc").unwrap();
        assert!(vimrc.redactions.is_empty());
    }

    #[test]
    fn allowlist_round_trips_through_toml() {
        let dir = tempfile::TempDir::new().unwrap();
        let path = dir.path().join("public-allowlist.toml");
        let list = Allowlist {
            generated: "2026-09-20T00:00:00Z".to_string(),
            files: vec![AllowedFile {
                path: ".gitconfig".to_string(),
                redactions: vec!["gitconfig-identity x2".to_string()],
            }],
            withheld: vec![AllowedFile {
                path: ".ssh/config".to_string(),
                redactions: vec!["public.exclude '.ssh/**'".to_string()],
            }],
        };
        list.save(&path).unwrap();

        let text = fs::read_to_string(&path).unwrap();
        assert!(
            text.starts_with("# Generated by"),
            "header should explain the file"
        );

        let back = Allowlist::load(&path).unwrap().unwrap();
        assert!(back.contains(Path::new(".gitconfig")));
        assert!(!back.contains(Path::new(".ssh/config")));
        assert_eq!(back.files[0].redactions, vec!["gitconfig-identity x2"]);
    }

    #[test]
    fn missing_allowlist_loads_as_none() {
        let dir = tempfile::TempDir::new().unwrap();
        assert!(Allowlist::load(&dir.path().join("absent.toml"))
            .unwrap()
            .is_none());
    }

    #[test]
    fn user_rules_run_after_builtins() {
        let public = PublicConfig {
            redact: vec![RedactRule {
                name: "license-key".to_string(),
                path: Some("*.conf".to_string()),
                pattern: r"(?m)^(license\s*=\s*).+$".to_string(),
                replacement: "${1}<redacted>".to_string(),
            }],
            ..Default::default()
        };
        let (out, applied) = redact_text_t(Path::new("app.conf"), "license = ABCD-1234\n", &public);
        assert!(out.contains("license = <redacted>"));
        assert!(applied.iter().any(|r| r.rule == "license-key"));
    }

    #[test]
    fn a_broken_user_regex_is_skipped_not_fatal() {
        let public = PublicConfig {
            redact: vec![RedactRule {
                name: "bad".to_string(),
                path: None,
                pattern: "([unclosed".to_string(),
                replacement: "x".to_string(),
            }],
            ..Default::default()
        };
        let (out, applied) = redact_text_t(Path::new("a.conf"), "keep me\n", &public);
        assert_eq!(out, "keep me\n");
        assert!(applied.is_empty());
    }
}
